# Generated by Django 5.1.2 on 2024-11-17 14:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('team_id', models.AutoField(primary_key=True, serialize=False)),
                ('team_name', models.CharField(max_length=100, unique=True)),
                ('team_league', models.CharField(max_length=100)),
                ('team_score', models.IntegerField(default=0)),
                ('team_goals', models.IntegerField(default=0)),
                ('team_assists', models.IntegerField(default=0)),
                ('team_red_card', models.IntegerField(default=0)),
                ('team_yellow_card', models.IntegerField(default=0)),
                ('team_fault', models.IntegerField(default=0)),
                ('team_tackling', models.IntegerField(default=0)),
                ('team_index', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('player_id', models.AutoField(primary_key=True, serialize=False)),
                ('player_name', models.CharField(max_length=100)),
                ('player_nationality', models.CharField(blank=True, max_length=100, null=True)),
                ('player_age', models.IntegerField(blank=True, null=True)),
                ('player_goals', models.IntegerField(default=0)),
                ('player_assists', models.IntegerField(default=0)),
                ('player_red_card', models.IntegerField(default=0)),
                ('player_yellow_card', models.IntegerField(default=0)),
                ('player_fault', models.IntegerField(default=0)),
                ('player_tackling', models.IntegerField(default=0)),
                ('player_index', models.TextField(blank=True, null=True)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='football_app.team')),
            ],
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('match_id', models.AutoField(primary_key=True, serialize=False)),
                ('home_team_goals', models.IntegerField(default=0)),
                ('away_team_goals', models.IntegerField(default=0)),
                ('league_name', models.CharField(max_length=100)),
                ('season_year', models.CharField(max_length=9)),
                ('away_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='away_matches', to='football_app.team')),
                ('home_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='home_matches', to='football_app.team')),
            ],
        ),
        migrations.CreateModel(
            name='Coach',
            fields=[
                ('coach_id', models.AutoField(primary_key=True, serialize=False)),
                ('coach_name', models.CharField(max_length=100)),
                ('coach_nationality', models.CharField(blank=True, max_length=100, null=True)),
                ('coach_age', models.IntegerField(blank=True, null=True)),
                ('coach_index', models.TextField(blank=True, null=True)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='football_app.team')),
            ],
        ),
        migrations.CreateModel(
            name='Participation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goals', models.IntegerField(default=0)),
                ('assists', models.IntegerField(default=0)),
                ('red_cards', models.IntegerField(default=0)),
                ('yellow_cards', models.IntegerField(default=0)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='football_app.match')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='football_app.player')),
            ],
            options={
                'ordering': ['-goals', '-assists'],
                'unique_together': {('player', 'match')},
            },
        ),
    ]
