# Generated by Django 5.1.2 on 2024-11-22 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('football_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
    ]
