# Generated by Django 5.1.2 on 2024-11-22 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('football_app', '0002_match_is_completed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coach',
            name='coach_index',
        ),
        migrations.RemoveField(
            model_name='player',
            name='player_fault',
        ),
        migrations.RemoveField(
            model_name='player',
            name='player_index',
        ),
        migrations.RemoveField(
            model_name='player',
            name='player_tackling',
        ),
        migrations.RemoveField(
            model_name='team',
            name='team_fault',
        ),
        migrations.RemoveField(
            model_name='team',
            name='team_index',
        ),
        migrations.RemoveField(
            model_name='team',
            name='team_tackling',
        ),
    ]
